### ISSUE TITLE
Support 1106 models api

### ISSUE THREAD

**Issue by TieWay59** [jakecyr/openai-function-calling#11]
## Overview

OpenAI has released new API https://platform.openai.com/docs/api-reference/chat/create 

It moves `function` feature into `tools`. 

@jakecyr Do you have plan to update this package to fit this new change? I love this design idea, and it has really helped me. 

## Why make this change?

This may be useful if new users come and see this project is up to date.

I'd love to help if it's not your plan ~

**Comment by jakecyr** [comment]
> ## Overview
> OpenAI has released new API https://platform.openai.com/docs/api-reference/chat/create
> 
> It moves `function` feature into `tools`.
> 
> @jakecyr Do you have plan to update this package to fit this new change? I love this design idea, and it has really helped me.
> 
> ## Why make this change?
> This may be useful if new users come and see this project is up to date.
> 
> I'd love to help if it's not your plan ~

Hi @TieWay59! Thank you for the reminder. I'd be happy to update the library to support the the new API.

**Comment by jakecyr** [comment]
@TieWay59 Do you want to review my PR to make sure it solves your use case?

https://github.com/jakecyr/openai-function-calling/pull/12

**Comment by TieWay59** [comment]
@jakecyr sorry for the late reply, I was at home this weekend, so I can't test right now on the case my work uses. I'll give you more feedback later next week. I hope this won't stop your plan, and please feel free to finish it if I'm too late.
