### ISSUE TITLE
ImportError: cannot import name 'FunctionInferrer' from 'openai_function_calling'

### ISSUE THREAD

**Issue by skhaz** [jakecyr/openai-function-calling#17]
The example seems not to work. Looking at the code, it appears that "FunctionInferrer" exists but is not exported.

**Comment by jakecyr** [comment]
Hey @skhaz! Thank you for the bug report. I updated the [unit tests](https://github.com/jakecyr/openai-function-calling/blob/master/tests/test_function_inferer.py#L9) to import `FunctionInferrer` from the root module to verify it's importable from there and also the `openai_function_calling.function_inferrer` module itself.

Can you post your code and more info about your environment so I can help you get setup?

**Comment by jakecyr** [comment]
Closing for now. Feel free to reopen if it's still an issue!
