### ISSUE TITLE
Need more python version support 3.12

### ISSUE THREAD

**Issue by windy** [jakecyr/openai-function-calling#19]
The current project's supported Python range (>=3.11,<4.0) is not compatible with some of the required packages Python requirement:
  - openai-function-calling requires Python <=3.12,>=3.9, so it will not be satisfied for Python >3.12,<4.0

Because no versions of openai-function-calling match >2.1.0,<3.0.0
 and openai-function-calling (2.1.0) requires Python <=3.12,>=3.9, openai-function-calling is forbidden.
So, because heracles depends on openai-function-calling (^2.1.0), version solving failed.

**Comment by jakecyr** [comment]
I increased the range to >=3.9, <3.13 in this [MR](https://github.com/jakecyr/openai-function-calling/pull/21)
