### ISSUE TITLE
docstring-parser need support >=0.16

### ISSUE THREAD

**Issue by windy** [jakecyr/openai-function-calling#20]
It's conflict with instructor (1.3.6)

Because instructor (1.3.6) depends on docstring-parser (>=0.16,<0.17)
 and openai-function-calling (2.1.0) depends on docstring-parser (>=0.15,<0.16), instructor (1.3.6) is incompatible with openai-function-calling

**Comment by jakecyr** [comment]
Created a [PR](https://github.com/jakecyr/openai-function-calling/pull/22) with the update.

**Comment by windy** [comment]
cool, very fast 👍
