### ISSUE TITLE
Add Python 3.13 Support

### ISSUE THREAD

**Issue by 0xrohitgarg** [jakecyr/openai-function-calling#24]
### Description:
The `openai-function-calling` package currently specifies Python version support as `>=3.9, <3.13`. This limitation causes compatibility issues for users running Python 3.13, preventing them from installing or using the package.

### Steps to Reproduce:
- Install Python 3.13 on your machine.
- Attempt to install openai-function-calling.
- Observe that installation fails due to the version restriction.

**Comment by jakecyr** [comment]
Published a new version with 3.13 support:

https://pypi.org/project/openai-function-calling/2.3.0/
