### ISSUE TITLE
broken pip install 

### ISSUE THREAD

**Issue by yogeshchandrasekharuni** [jakecyr/openai-function-calling#8]
**Describe the bug**
Failing to install the packages

**To Reproduce**
1. pip install openai-function-calling
2. See error

**Expected behavior**
Should have installed the package

**Env**
 - Python 3.9.15

**Comment by yogeshchandrasekharuni** [comment]
I see that the package requires python 3.10 or later.. closing!

**Comment by jakecyr** [comment]
Hello! I have increased version range to include Python 3.9 in the latest release.
